name: docker

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: bschrib
          password: ${{ secrets.GHCR_PAT }}
      - uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          push: true
          tags: ghcr.io/bschrib/schoolday:latest
